config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :bikes do
    resources :bookings
  end
  get '/dashboard', to: 'pages#dashboard', :defaults => { bike: true }
  get '/bookings/:id/accept', to: 'bookings#accept', as: :accept
  get '/bookings/:id/decline', to: 'bookings#decline', as: :decline
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :bookers, through: :bookings, source: :user
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # validates :category, presence: true
  # validates :size, presence: true
  # validates :address, presence: true
  # validates :price, presence: true, numericality: true

end


# inclusion: { in: %w(road mountain hybrid city lady cruiser cargo)}
# bike.renters

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bike
end

app/models/user.rb
class User < ApplicationRecord

  has_many :bikes
  has_many :bookings
  has_many :booked_bikes, through: :bookings, source: :bike
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :photo, PhotoUploader
#   validates :first_name, presence: true, allow_blank: false
#   validates :last_name, presence: true, allow_blank: false

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  after_action :store_location

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end



  def store_location
    # store last url as long as it isn't a /users path
    session[:previous_url] = request.fullpath unless request.fullpath =~ /\/users/
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_bike, only: [:edit, :update, :show]

  def index
    if params[:location]
      @bikes = Bike.where("address iLIKE ?", "%#{params[:location]}%").where.not(latitude: nil, longitude: nil)
    else
      @bikes = Bike.where.not(latitude: nil, longitude: nil)
    end
    # @bikes = Bike.where.not(latitude: nil, longitude: nil)

    @markers = @bikes.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }

    end
  end

  def show
    @bike = Bike.find(params[:id])
    @booking = Booking.new
    @markers = [{ lat: @bike.latitude, lng: @bike.longitude }]

  end

  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user

    if @bike.save
      redirect_to bike_path(@bike)
    else
      render :new
    end
  end

  def edit

  end

  def update
    bike_params
    @bike.update(bike_params)
    redirect_to bike_path(@bike)

  end

  def destroy
    @bike = Bike.find(params[:id])
    @bike.destroy
    redirect_to dashboard_path
  end



  private

  def bike_params
    params.require(:bike).permit(:name, :description, :size, :category, :price, :address, :photo)
  end

  def set_bike
    @bike = Bike.find(params[:id])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @bike = Bike.find(params[:bike_id])
    @booking = Booking.new(booking_params)
    @booking.bike = @bike
    @booking.status = "pending"
    @booking.user_id = current_user.id
    if @booking.save
      redirect_to bike_path(@bike)
    else
      render "bikes/show"
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "accepted"
    @booking.save
    redirect_to dashboard_path(bookings: true)
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.status = "declined"
    @booking.save
    redirect_to dashboard_path(bookings: true)
  end

  private



  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @bookings = current_user.bookings
    @bikes = current_user.bikes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_form.html.erb
<%= simple_form_for(bike) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="forminputs">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :category, :collection => %w[mountain-bike city-bike tandem]%>
      <%= f.input :size, :collection => %w[adult child]%>
      <%= f.input :price %>
      <%= f.input :address %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
    </div>

    <div class="text-center">
      <%= f.button :submit, class: "btn btn-all" %>
    </div>

<% end %>

app/views/bikes/edit.html.erb
<div class="wrapper">
  <div class="content">
    <div class="description">
      <h1>Your bike status</h1>
      <p>You can update your post at all times</p>
    </div>
    <div class="update-form">
      <div class="row">
        <div class="col-xs-6 col-xs-offset-3">
          <%= render 'form', bike: @bike %>
            <%= link_to 'Back', bikes_path , class: "btn btn-success" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bikes/index.html.erb
<div class="wrapper-index">
  <div class="container-index">

    <div class="container-fluid">
      <div class="row">
        <% @bikes.each do |bike| %>
        <div class="col-xs-12 col-sm-4">
          <% if bike.photo? %>
            <% photo = cl_image_path bike.photo %>
          <% else %>
            <% photo = "https://images.pexels.com/photos/276517/pexels-photo-276517.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" %>
          <% end %>
          <div class= "card" style= "background-image:linear-gradient(-225deg, rgba(0,0,0,0.2) 0%, rgba(69,68,68,0.8) 100%), url('<%= photo %>')">
            <div class= "card_content">
              <%= link_to bike.name, bike_path(bike) %>
              <i class="far fa-heart heart"></i>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>

    <% if @bikes.any? %>
    <div
    class="index-map"
    id="map"
    data-markers="<%= @markers.to_json %>"
    >
  </div>
  <% end %>
</div>

app/views/bikes/new.html.erb
<div class="wrapper">
  <div class="content">

    <div class="description">
      <h1>Post your bike</h1>
      <p>Rent your bike in one click</p>
    </div>

    <div class="form">
      <div class="row">
        <div class="col-xs-6 col-xs-offset-3">
          <%= render 'form', bike: @bike %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/bikes/show.html.erb
<div class="banner-wrapper">
<% bike_photo =  @bike.photo? ? @bike.photo : "https://images.unsplash.com/photo-1496150590317-f8d952453f93?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=961edb326df737a36e5eafcae013b5fe&auto=format&fit=crop&w=1350&q=80" %>
  <div class="banner-show content-bottom" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path bike_photo, quality: "auto" %>');">
  </div>

  <div class="flex-container">
    <div class="left">

      <div class="text-flex">
        <div class="name">
          <h1><%= @bike.name %></h1>
        </div>
        <div class="header">
        <% if @bike.user.photo? %>
          <p><%= cl_image_tag @bike.user.photo, class: "avatar" %></p>
          <p><%= @bike.user.name %></p>
          <% end %>
        </div>
      </div>
      <hr>
      </hr>
      <div class="text">


        <p><%= @bike.description %></p>
        <p>Category: <%= @bike.category %></p>
        <p>Size: <%= @bike.size %></p>
        <p>Location: <%= @bike.address %></p>
      </div>


      <div class="map-holder map-show">
        <div id="map" class="show-map" style="width: 100%; height: 500px;" data-markers="<%= @markers.to_json %>">
        </div>
      </div>

    </div>
    <div class="right booking-container">
      <h3>£ <%= @bike.price %> /day</h3>
      <% if current_user == @bike.user %>
        <p>You have <%= @bike.bookings.count %> bookings for this bike</p>
      <% elsif user_signed_in? %>
        <%= simple_form_for [@bike, @booking], :method => :post do |f|%>
          <%= f.input :start_date, as: :string, input_html: {class: 'flatpickr'} %>
          <%= f.input :end_date, as: :string, input_html: {class: 'flatpickr'} %>
          <%= f.submit "Request to book", class: "btn-request", id:"sweet-alert-demo" %>
        <% end %>
      <% else %>
        <%= link_to "Sign In",  new_user_session_path, class: "btn-signup" %>
      <% end %>
    </div>
  </div>














   <!-- <p style="margin-left: 4%;">City kids bike - Boys</p> -->
        <!-- <p><i class="fas fa-check icon-space"></i>Available: 24May till 30May</p>
         -->
    <!--   <hr class="line">
      <div class="center"> -->
        <!-- date form -->
        <!-- <a href="#" class="btn_request">Request booking</a> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Bikes on the Go</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
    <!-- <%#= stylesheet_pack_tag 'application', media: 'all' %> Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- font awesome cdn -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_API_SERVER_KEY']}" %>
    <%#= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%# yield(:after_js) %>
    <%= javascript_pack_tag "map" %> <!-- add this line -->
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="dashboard">
  <div class="row">
    <div class="col-xs-12 col-md-3">
      <div class="user-profile text-center">
        <% if current_user.photo? %>
          <% photo = cl_image_path current_user.photo %>
        <% else %>
          <% photo = "https://orig00.deviantart.net/c91f/f/2010/014/b/c/avatar_by_eggar919.jpg" %>
        <% end %>
        <div class="avatar" style="background-image: url(<%= photo %>);"></div>
        <h3><%= current_user.first_name %></h3>
        <h3><%= current_user.last_name %></h3>
        <p><%= current_user.email %></p>
        <%= link_to "Edit your profile", edit_user_registration_path %>
      </div>
    </div>



    <div class="dash_nav col-xs-12 col-md-9">

      <!-- Nav tabs -->
      <ul class="nav nav-tabs nav-justified" role="tablist">
        <li role="presentation" class="tab <%= "active" if params[:bikes] %>"><a href="#bikes" aria-controls="bikes" role="tab" data-toggle="tab">My Bikes</a></li>
        <li role="presentation" class="tab <%= "active" if params[:requests] %>"><a href="#requests" aria-controls="requests" role="tab" data-toggle="tab">Bikes that I have requested</a></li>
        <li role="presentation" class="tab <%= "active" if params[:bookings] %>"><a href="#bookings" aria-controls="bookings" role="tab" data-toggle="tab">Who wants my Bikes</a></li>
      </ul>


      <div class="tab-content">
        <div role="tabpanel" class="tab-pane <%= "active" if params[:bikes] %>" id="bikes">
          <% current_user.bikes.each do |bike| %>
          <li class="bike">
            <%= link_to bike_path(bike) do %>
              <%= cl_image_tag bike.photo, class: 'tab-image' %>
            <% end %>
            <div class="bike-details">
              <strong><%= bike.name %></strong>
              <p> <%= bike.description %></p>
            </div>
            <%= link_to '<i class="far fa-times-circle"></i>'.html_safe, bike_path(bike) , method: :delete, data: { confirm: "Are you sure you want to delete this bike?"} %>
          </li>
          <% end %>
        </div>
        <div role="tabpanel" class="tab-pane <%= "active" if params[:bookings] %>" id="bookings">
          <% current_user.bikes.each do |bike| %>
            <% bike.bookings.each do |booking| %>
              <li class="bike">
                <%= link_to bike_path(bike) do %>
                 <%= cl_image_tag booking.bike.photo, class: 'tab-image' %>
                <% end %>
                <div class="bike-details">
                  <p>Bike name: <strong><%= booking.bike.name %></strong></p>
                  <div class="requester">
                    <p>Requested by <strong><%= booking.user.name %></strong></p>
                    <%= cl_image_tag booking.user.photo, class: "avatar-small" %>
                  </div>
                  <div class="booking-dates">
                    <p>From: <strong><%= booking.start_date %></strong> <i class="fas fa-arrow-right"></i> To: <strong><%= booking.end_date %></strong></p>
                  </div>
                </div>
                <div class="manage-request text-center">
                  <% if booking.status == "accepted" %>
                    <p>You have <strong><%= booking.status %></strong>  this booking</p>
                    <%= link_to "Decline", decline_path(booking), class: "btn btn-danger" %>
                  <% elsif booking.status == "declined" %>
                    <p>You have <strong><%= booking.status %></strong>  this booking</p>
                    <%= link_to "Accept", accept_path(booking), class: "btn btn-success" %>
                  <% else %>
                      <!-- pending -->
                    <p>This request is <strong><%= booking.status %></strong> </p>
                    <%= link_to "Accept", accept_path(booking), class: "btn btn-success" %>
                    <%= link_to "Decline", decline_path(booking), class: "btn btn-danger" %>
                  <% end %>
                </div>
              </li>
            <% end %>
          <% end %>
        </div>
        <div role="tabpanel" class="tab-pane <%= "active" if params[:requests] %>" id="requests">
          <% current_user.bookings.each do |booking| %>
          <li class="bike">
            <div class="bike-photo">
              <%= link_to  bike_path(booking.bike) do %>
               <%= cl_image_tag booking.bike.photo, class: 'tab-image' %>
              <% end %>
              <div class="owner-picture">
                <%= cl_image_tag booking.bike.user.photo, class: "avatar-small" %>
              </div>
            </div>
            <div class="bike-details">
              <p>Bike name: <strong><%= booking.bike.name %></strong></p>
              <p>Bike Owner: <strong><%= booking.bike.user.name %></strong></p>
              <p>Location: <strong><%= booking.bike.address %></strong></p>
              <div class="booking-dates">
                <p>From: <strong><%= booking.start_date %></strong> <i class="fas fa-arrow-right"></i> To: <strong><%= booking.end_date %></strong></p>
              </div>
            </div>
            <div class="request-status">
              <p>This request is <strong><%= booking.status %></strong></p>
            </div>
          </li>
          <% end %>

        </div>
      </div>

    </div>

      </div>
    </div>
  </div>

  <%# content_for(:after_js) do  %>
    <!-- script>
      console.log($("#bookings"));
    </script> -->
  <%# end %>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>
<h1>Bikes on the Go</h1>

<!-- <p>Find me in app/views/pages/home.html.erb</p> -->

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.2) 0%, rgba(69,68,68,0.8) 100%), url(<%= image_path "bike2.jpg" %>);">

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
 <!--  <a href="/" class="navbar-wagon-brand">
    <img src="images/logo.png" alt="logo">
  </a> -->
  <%= link_to root_path do %>
   <i class="fas fa-bicycle" id="logo"></i>
  <% end %>

  <div class="search">
    <%= form_tag bikes_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :location, params[:location], class: "nav-inpu" %>
        <%= submit_tag "Search", :name => nil, class: "btn-all" %>
      </p>
    <% end %>
  </div>
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- <a href="/" class="navbar-wagon-item navbar-wagon-link">Home</a>
    <a href="/bikes" class="navbar-wagon-item navbar-wagon-link">Search</a> -->

      <% if user_signed_in? %>
        <%= link_to "Add bike", new_bike_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Log Out",  destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
            <%= link_to "Dashboard", dashboard_path(bikes: true), class: "navbar-wagon-item navbar-wagon-link" %>
      <% else %>
        <%= link_to "Sign In",  new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
    <!-- <a href="users/sign_in" class="navbar-wagon-item navbar-wagon-link">Sign in</a> -->

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
    <!--     <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"> -->
        <!-- <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul> -->
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li><%= link_to "Add bike", new_bike_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to "Log Out",  destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to "Dashboard", dashboard_path(bikes: true), class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% else %>
          <li><%= link_to "Sign In",  new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>